//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class aa_actions
    {
        public int aaid { get; set; }
        public byte rank { get; set; }
        public int reuse_time { get; set; }
        public int spell_id { get; set; }
        public byte target { get; set; }
        public byte nonspell_action { get; set; }
        public int nonspell_mana { get; set; }
        public int nonspell_duration { get; set; }
        public int redux_aa { get; set; }
        public sbyte redux_rate { get; set; }
        public int redux_aa2 { get; set; }
        public sbyte redux_rate2 { get; set; }
    }
}
