//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class aa_ability
    {
        public long id { get; set; }
        public string name { get; set; }
        public int category { get; set; }
        public int classes { get; set; }
        public int races { get; set; }
        public int drakkin_heritage { get; set; }
        public int deities { get; set; }
        public int status { get; set; }
        public int type { get; set; }
        public int charges { get; set; }
        public sbyte grant_only { get; set; }
        public int first_rank_id { get; set; }
        public byte enabled { get; set; }
    }
}
