//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class aa_effects
    {
        public long id { get; set; }
        public int aaid { get; set; }
        public byte slot { get; set; }
        public int effectid { get; set; }
        public int base1 { get; set; }
        public int base2 { get; set; }
    }
}
