//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class aa_ranks
    {
        public long id { get; set; }
        public int upper_hotkey_sid { get; set; }
        public int lower_hotkey_sid { get; set; }
        public int title_sid { get; set; }
        public int desc_sid { get; set; }
        public int cost { get; set; }
        public int level_req { get; set; }
        public int spell { get; set; }
        public int spell_type { get; set; }
        public int recast_time { get; set; }
        public int expansion { get; set; }
        public int prev_id { get; set; }
        public int next_id { get; set; }
    }
}
