//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int id { get; set; }
        public string name { get; set; }
        public string charname { get; set; }
        public long sharedplat { get; set; }
        public string password { get; set; }
        public int status { get; set; }
        public Nullable<long> lsaccount_id { get; set; }
        public byte gmspeed { get; set; }
        public byte revoked { get; set; }
        public long karma { get; set; }
        public string minilogin_ip { get; set; }
        public sbyte hideme { get; set; }
        public bool rulesflag { get; set; }
        public System.DateTime suspendeduntil { get; set; }
        public long time_creation { get; set; }
        public sbyte expansion { get; set; }
        public string ban_reason { get; set; }
        public string suspend_reason { get; set; }
    }
}
