//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public long taskid { get; set; }
        public long activityid { get; set; }
        public long step { get; set; }
        public byte activitytype { get; set; }
        public string text1 { get; set; }
        public string text2 { get; set; }
        public string text3 { get; set; }
        public long goalid { get; set; }
        public long goalmethod { get; set; }
        public Nullable<int> goalcount { get; set; }
        public long delivertonpc { get; set; }
        public int zoneid { get; set; }
        public bool optional { get; set; }
    }
}
