//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class adventure_template
    {
        public long id { get; set; }
        public string zone { get; set; }
        public byte zone_version { get; set; }
        public byte is_hard { get; set; }
        public byte is_raid { get; set; }
        public byte min_level { get; set; }
        public byte max_level { get; set; }
        public byte type { get; set; }
        public long type_data { get; set; }
        public int type_count { get; set; }
        public float assa_x { get; set; }
        public float assa_y { get; set; }
        public float assa_z { get; set; }
        public float assa_h { get; set; }
        public string text { get; set; }
        public long duration { get; set; }
        public long zone_in_time { get; set; }
        public int win_points { get; set; }
        public int lose_points { get; set; }
        public byte theme { get; set; }
        public int zone_in_zone_id { get; set; }
        public float zone_in_x { get; set; }
        public float zone_in_y { get; set; }
        public short zone_in_object_id { get; set; }
        public float dest_x { get; set; }
        public float dest_y { get; set; }
        public float dest_z { get; set; }
        public float dest_h { get; set; }
        public long graveyard_zone_id { get; set; }
        public float graveyard_x { get; set; }
        public float graveyard_y { get; set; }
        public float graveyard_z { get; set; }
    }
}
