//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class adventure_details
    {
        public long id { get; set; }
        public int adventure_id { get; set; }
        public int instance_id { get; set; }
        public int count { get; set; }
        public int assassinate_count { get; set; }
        public byte status { get; set; }
        public long time_created { get; set; }
        public long time_zoned { get; set; }
        public long time_completed { get; set; }
    }
}
