//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class adventure_stats
    {
        public long player_id { get; set; }
        public int guk_wins { get; set; }
        public int mir_wins { get; set; }
        public int mmc_wins { get; set; }
        public int ruj_wins { get; set; }
        public int tak_wins { get; set; }
        public int guk_losses { get; set; }
        public int mir_losses { get; set; }
        public int mmc_losses { get; set; }
        public int ruj_losses { get; set; }
        public int tak_losses { get; set; }
    }
}
