//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class altadv_vars
    {
        public int skill_id { get; set; }
        public string name { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> max_level { get; set; }
        public long hotkey_sid { get; set; }
        public long hotkey_sid2 { get; set; }
        public long title_sid { get; set; }
        public long desc_sid { get; set; }
        public byte type { get; set; }
        public long spellid { get; set; }
        public long prereq_skill { get; set; }
        public long prereq_minpoints { get; set; }
        public long spell_type { get; set; }
        public long spell_refresh { get; set; }
        public long classes { get; set; }
        public long berserker { get; set; }
        public long class_type { get; set; }
        public sbyte cost_inc { get; set; }
        public int aa_expansion { get; set; }
        public long special_category { get; set; }
        public byte sof_type { get; set; }
        public sbyte sof_cost_inc { get; set; }
        public byte sof_max_level { get; set; }
        public long sof_next_skill { get; set; }
        public byte clientver { get; set; }
        public long account_time_required { get; set; }
        public byte sof_current_level { get; set; }
        public long sof_next_id { get; set; }
        public byte level_inc { get; set; }
    }
}
