//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_data
    {
        public long level { get; set; }
        public long @class { get; set; }
        public double hp { get; set; }
        public double mana { get; set; }
        public double end { get; set; }
        public double unk1 { get; set; }
        public double unk2 { get; set; }
        public double hp_fac { get; set; }
        public double mana_fac { get; set; }
        public double end_fac { get; set; }
    }
}
