//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class blocked_spells
    {
        public int id { get; set; }
        public int spellid { get; set; }
        public sbyte type { get; set; }
        public int zoneid { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float x_diff { get; set; }
        public float y_diff { get; set; }
        public float z_diff { get; set; }
        public string message { get; set; }
        public string description { get; set; }
    }
}
