//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bot_buffs
    {
        public long buffs_index { get; set; }
        public long bot_id { get; set; }
        public long spell_id { get; set; }
        public byte caster_level { get; set; }
        public long duration_formula { get; set; }
        public long tics_remaining { get; set; }
        public long poison_counters { get; set; }
        public long disease_counters { get; set; }
        public long curse_counters { get; set; }
        public long corruption_counters { get; set; }
        public long numhits { get; set; }
        public long melee_rune { get; set; }
        public long magic_rune { get; set; }
        public long dot_rune { get; set; }
        public bool persistent { get; set; }
        public int caston_x { get; set; }
        public int caston_y { get; set; }
        public int caston_z { get; set; }
        public long extra_di_chance { get; set; }
        public int instrument_mod { get; set; }
    
        public virtual bot_data bot_data { get; set; }
    }
}
