//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bot_spell_casting_chances
    {
        public int id { get; set; }
        public byte spell_type_index { get; set; }
        public byte class_id { get; set; }
        public byte stance_index { get; set; }
        public byte nHSND_value { get; set; }
        public byte pH_value { get; set; }
        public byte pS_value { get; set; }
        public byte pHS_value { get; set; }
        public byte pN_value { get; set; }
        public byte pHN_value { get; set; }
        public byte pSN_value { get; set; }
        public byte pHSN_value { get; set; }
        public byte pD_value { get; set; }
        public byte pHD_value { get; set; }
        public byte pSD_value { get; set; }
        public byte pHSD_value { get; set; }
        public byte pND_value { get; set; }
        public byte pHND_value { get; set; }
        public byte pSND_value { get; set; }
        public byte pHSND_value { get; set; }
    }
}
