//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botbuffs___
    {
        public long BotBuffId { get; set; }
        public long BotId { get; set; }
        public long SpellId { get; set; }
        public long CasterLevel { get; set; }
        public long DurationFormula { get; set; }
        public long TicsRemaining { get; set; }
        public long PoisonCounters { get; set; }
        public long DiseaseCounters { get; set; }
        public long CurseCounters { get; set; }
        public long CorruptionCounters { get; set; }
        public long HitCount { get; set; }
        public long MeleeRune { get; set; }
        public long MagicRune { get; set; }
        public long DeathSaveSuccessChance { get; set; }
        public long CasterAARank { get; set; }
        public bool Persistent { get; set; }
    
        public virtual bots_old bots_old { get; set; }
    }
}
