//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botgroup_old
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public botgroup_old()
        {
            this.botgroupmembers_old = new HashSet<botgroupmembers_old>();
        }
    
        public long BotGroupId { get; set; }
        public long BotGroupLeaderBotId { get; set; }
        public string BotGroupName { get; set; }
    
        public virtual bots_old bots_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<botgroupmembers_old> botgroupmembers_old { get; set; }
    }
}
