//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botgroupmembers_old
    {
        public long BotGroupMemberId { get; set; }
        public long BotGroupId { get; set; }
        public long BotId { get; set; }
    
        public virtual botgroup_old botgroup_old { get; set; }
        public virtual bots_old bots_old { get; set; }
    }
}
