//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botinventory_old
    {
        public long BotInventoryID { get; set; }
        public long BotID { get; set; }
        public int SlotID { get; set; }
        public long ItemID { get; set; }
        public Nullable<byte> charges { get; set; }
        public long color { get; set; }
        public int augslot1 { get; set; }
        public int augslot2 { get; set; }
        public int augslot3 { get; set; }
        public int augslot4 { get; set; }
        public Nullable<int> augslot5 { get; set; }
        public bool instnodrop { get; set; }
    
        public virtual bots_old bots_old { get; set; }
    }
}
