//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botpets_old
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public botpets_old()
        {
            this.botpetbuffs_old = new HashSet<botpetbuffs_old>();
            this.botpetinventory_old = new HashSet<botpetinventory_old>();
        }
    
        public long BotPetsId { get; set; }
        public long PetId { get; set; }
        public long BotId { get; set; }
        public string Name { get; set; }
        public int Mana { get; set; }
        public int HitPoints { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<botpetbuffs_old> botpetbuffs_old { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<botpetinventory_old> botpetinventory_old { get; set; }
        public virtual bots_old bots_old { get; set; }
    }
}
