//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botpetinventory_old
    {
        public long BotPetInventoryId { get; set; }
        public long BotPetsId { get; set; }
        public long ItemId { get; set; }
    
        public virtual botpets_old botpets_old { get; set; }
    }
}
