//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class botpetbuffs_old
    {
        public long BotPetBuffId { get; set; }
        public long BotPetsId { get; set; }
        public long SpellId { get; set; }
        public long CasterLevel { get; set; }
        public long Duration { get; set; }
    
        public virtual botpets_old botpets_old { get; set; }
    }
}
