//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug
    {
        public long id { get; set; }
        public string zone { get; set; }
        public string name { get; set; }
        public string ui { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public string type { get; set; }
        public byte flag { get; set; }
        public string target { get; set; }
        public string bug1 { get; set; }
        public System.DateTime date { get; set; }
        public byte status { get; set; }
    }
}
