//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_pet_info
    {
        public int char_id { get; set; }
        public int pet { get; set; }
        public string petname { get; set; }
        public int petpower { get; set; }
        public int spell_id { get; set; }
        public int hp { get; set; }
        public int mana { get; set; }
        public float size { get; set; }
    }
}
