//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_material
    {
        public long id { get; set; }
        public byte slot { get; set; }
        public byte blue { get; set; }
        public byte green { get; set; }
        public byte red { get; set; }
        public byte use_tint { get; set; }
        public long color { get; set; }
    }
}
