//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_corpse_items
    {
        public long corpse_id { get; set; }
        public long equip_slot { get; set; }
        public Nullable<long> item_id { get; set; }
        public Nullable<long> charges { get; set; }
        public Nullable<long> aug_1 { get; set; }
        public Nullable<long> aug_2 { get; set; }
        public Nullable<long> aug_3 { get; set; }
        public Nullable<long> aug_4 { get; set; }
        public Nullable<long> aug_5 { get; set; }
        public Nullable<long> aug_6 { get; set; }
        public short attuned { get; set; }
    }
}
