//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_alternate_abilities_old
    {
        public long id { get; set; }
        public int slot { get; set; }
        public int aa_id { get; set; }
        public int aa_value { get; set; }
        public int charges { get; set; }
    }
}
