//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class char_create_combinations
    {
        public long allocation_id { get; set; }
        public long race { get; set; }
        public long @class { get; set; }
        public long deity { get; set; }
        public long start_zone { get; set; }
        public long expansions_req { get; set; }
    }
}
