//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_bandolier
    {
        public long id { get; set; }
        public byte bandolier_id { get; set; }
        public byte bandolier_slot { get; set; }
        public long item_id { get; set; }
        public long icon { get; set; }
        public string bandolier_name { get; set; }
    }
}
