//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_data__
    {
        public long id { get; set; }
        public int account_id { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string title { get; set; }
        public string suffix { get; set; }
        public long zone_id { get; set; }
        public long zone_instance { get; set; }
        public float y { get; set; }
        public float x { get; set; }
        public float z { get; set; }
        public float heading { get; set; }
        public byte gender { get; set; }
        public int race { get; set; }
        public byte @class { get; set; }
        public long level { get; set; }
        public long deity { get; set; }
        public long birthday { get; set; }
        public long last_login { get; set; }
        public long time_played { get; set; }
        public byte level2 { get; set; }
        public byte anon { get; set; }
        public byte gm { get; set; }
        public long face { get; set; }
        public byte hair_color { get; set; }
        public byte hair_style { get; set; }
        public byte beard { get; set; }
        public byte beard_color { get; set; }
        public byte eye_color_1 { get; set; }
        public byte eye_color_2 { get; set; }
        public long drakkin_heritage { get; set; }
        public long drakkin_tattoo { get; set; }
        public long drakkin_details { get; set; }
        public byte ability_time_seconds { get; set; }
        public byte ability_number { get; set; }
        public byte ability_time_minutes { get; set; }
        public byte ability_time_hours { get; set; }
        public long exp { get; set; }
        public long aa_points_spent { get; set; }
        public long aa_exp { get; set; }
        public long aa_points { get; set; }
        public long group_leadership_exp { get; set; }
        public long raid_leadership_exp { get; set; }
        public long group_leadership_points { get; set; }
        public long raid_leadership_points { get; set; }
        public long points { get; set; }
        public long cur_hp { get; set; }
        public long mana { get; set; }
        public long endurance { get; set; }
        public long intoxication { get; set; }
        public long str { get; set; }
        public long sta { get; set; }
        public long cha { get; set; }
        public long dex { get; set; }
        public long @int { get; set; }
        public long agi { get; set; }
        public long wis { get; set; }
        public long zone_change_count { get; set; }
        public long toxicity { get; set; }
        public long hunger_level { get; set; }
        public long thirst_level { get; set; }
        public long ability_up { get; set; }
        public long ldon_points_guk { get; set; }
        public long ldon_points_mir { get; set; }
        public long ldon_points_mmc { get; set; }
        public long ldon_points_ruj { get; set; }
        public long ldon_points_tak { get; set; }
        public long ldon_points_available { get; set; }
        public long tribute_time_remaining { get; set; }
        public long career_tribute_points { get; set; }
        public long tribute_points { get; set; }
        public long tribute_active { get; set; }
        public byte pvp_status { get; set; }
        public long pvp_kills { get; set; }
        public long pvp_deaths { get; set; }
        public long pvp_current_points { get; set; }
        public long pvp_career_points { get; set; }
        public long pvp_best_kill_streak { get; set; }
        public long pvp_worst_death_streak { get; set; }
        public long pvp_current_kill_streak { get; set; }
        public long pvp2 { get; set; }
        public long pvp_type { get; set; }
        public long show_helm { get; set; }
        public byte group_auto_consent { get; set; }
        public byte raid_auto_consent { get; set; }
        public byte guild_auto_consent { get; set; }
        public byte leadership_exp_on { get; set; }
        public long RestTimer { get; set; }
        public long air_remaining { get; set; }
        public long autosplit_enabled { get; set; }
        public bool lfp { get; set; }
        public bool lfg { get; set; }
        public string mailkey { get; set; }
        public byte xtargets { get; set; }
        public sbyte firstlogon { get; set; }
        public long e_aa_effects { get; set; }
        public long e_percent_to_aa { get; set; }
        public long e_expended_aa_spent { get; set; }
    }
}
