//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_buffs
    {
        public long character_id { get; set; }
        public byte slot_id { get; set; }
        public int spell_id { get; set; }
        public byte caster_level { get; set; }
        public string caster_name { get; set; }
        public int ticsremaining { get; set; }
        public long counters { get; set; }
        public long numhits { get; set; }
        public long melee_rune { get; set; }
        public long magic_rune { get; set; }
        public byte persistent { get; set; }
        public int dot_rune { get; set; }
        public int caston_x { get; set; }
        public int caston_y { get; set; }
        public int caston_z { get; set; }
        public int ExtraDIChance { get; set; }
        public int instrument_mod { get; set; }
    }
}
