//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class char_create_point_allocations
    {
        public long id { get; set; }
        public long base_str { get; set; }
        public long base_sta { get; set; }
        public long base_dex { get; set; }
        public long base_agi { get; set; }
        public long base_int { get; set; }
        public long base_wis { get; set; }
        public long base_cha { get; set; }
        public long alloc_str { get; set; }
        public long alloc_sta { get; set; }
        public long alloc_dex { get; set; }
        public long alloc_agi { get; set; }
        public long alloc_int { get; set; }
        public long alloc_wis { get; set; }
        public long alloc_cha { get; set; }
    }
}
