//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_backup
    {
        public long id { get; set; }
        public byte backupreason { get; set; }
        public long charid { get; set; }
        public long account_id { get; set; }
        public string name { get; set; }
        public byte[] profile { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public short zoneid { get; set; }
        public byte[] alt_adv { get; set; }
        public System.DateTime ts { get; set; }
        public sbyte @class { get; set; }
        public int level { get; set; }
    }
}
