//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_corpses
    {
        public long id { get; set; }
        public long charid { get; set; }
        public string charname { get; set; }
        public short zone_id { get; set; }
        public int instance_id { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float heading { get; set; }
        public System.DateTime time_of_death { get; set; }
        public Nullable<byte> is_rezzed { get; set; }
        public sbyte is_buried { get; set; }
        public sbyte was_at_graveyard { get; set; }
        public Nullable<sbyte> is_locked { get; set; }
        public Nullable<long> exp { get; set; }
        public Nullable<long> size { get; set; }
        public Nullable<long> level { get; set; }
        public Nullable<long> race { get; set; }
        public Nullable<long> gender { get; set; }
        public Nullable<long> @class { get; set; }
        public Nullable<long> deity { get; set; }
        public Nullable<long> texture { get; set; }
        public Nullable<long> helm_texture { get; set; }
        public Nullable<long> copper { get; set; }
        public Nullable<long> silver { get; set; }
        public Nullable<long> gold { get; set; }
        public Nullable<long> platinum { get; set; }
        public Nullable<long> hair_color { get; set; }
        public Nullable<long> beard_color { get; set; }
        public Nullable<long> eye_color_1 { get; set; }
        public Nullable<long> eye_color_2 { get; set; }
        public Nullable<long> hair_style { get; set; }
        public Nullable<long> face { get; set; }
        public Nullable<long> beard { get; set; }
        public Nullable<long> drakkin_heritage { get; set; }
        public Nullable<long> drakkin_tattoo { get; set; }
        public Nullable<long> drakkin_details { get; set; }
        public Nullable<long> wc_1 { get; set; }
        public Nullable<long> wc_2 { get; set; }
        public Nullable<long> wc_3 { get; set; }
        public Nullable<long> wc_4 { get; set; }
        public Nullable<long> wc_5 { get; set; }
        public Nullable<long> wc_6 { get; set; }
        public Nullable<long> wc_7 { get; set; }
        public Nullable<long> wc_8 { get; set; }
        public Nullable<long> wc_9 { get; set; }
    }
}
