//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_currency
    {
        public long id { get; set; }
        public long platinum { get; set; }
        public long gold { get; set; }
        public long silver { get; set; }
        public long copper { get; set; }
        public long platinum_bank { get; set; }
        public long gold_bank { get; set; }
        public long silver_bank { get; set; }
        public long copper_bank { get; set; }
        public long platinum_cursor { get; set; }
        public long gold_cursor { get; set; }
        public long silver_cursor { get; set; }
        public long copper_cursor { get; set; }
        public long radiant_crystals { get; set; }
        public long career_radiant_crystals { get; set; }
        public long ebon_crystals { get; set; }
        public long career_ebon_crystals { get; set; }
    }
}
