//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_pet_buffs
    {
        public int char_id { get; set; }
        public int pet { get; set; }
        public int slot { get; set; }
        public int spell_id { get; set; }
        public sbyte caster_level { get; set; }
        public string castername { get; set; }
        public int ticsremaining { get; set; }
        public int counters { get; set; }
        public int numhits { get; set; }
        public int rune { get; set; }
        public byte instrument_mod { get; set; }
    }
}
