//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_skill
    {
        public int @class { get; set; }
        public string name { get; set; }
        public Nullable<int> skill_0 { get; set; }
        public Nullable<int> skill_1 { get; set; }
        public Nullable<int> skill_2 { get; set; }
        public Nullable<int> skill_3 { get; set; }
        public Nullable<int> skill_4 { get; set; }
        public Nullable<int> skill_5 { get; set; }
        public Nullable<int> skill_6 { get; set; }
        public Nullable<int> skill_7 { get; set; }
        public Nullable<int> skill_8 { get; set; }
        public Nullable<int> skill_9 { get; set; }
        public Nullable<int> skill_10 { get; set; }
        public Nullable<int> skill_11 { get; set; }
        public Nullable<int> skill_12 { get; set; }
        public Nullable<int> skill_13 { get; set; }
        public Nullable<int> skill_14 { get; set; }
        public Nullable<int> skill_15 { get; set; }
        public Nullable<int> skill_16 { get; set; }
        public Nullable<int> skill_17 { get; set; }
        public Nullable<int> skill_18 { get; set; }
        public Nullable<int> skill_19 { get; set; }
        public Nullable<int> skill_20 { get; set; }
        public Nullable<int> skill_21 { get; set; }
        public Nullable<int> skill_22 { get; set; }
        public Nullable<int> skill_23 { get; set; }
        public Nullable<int> skill_24 { get; set; }
        public Nullable<int> skill_25 { get; set; }
        public Nullable<int> skill_26 { get; set; }
        public Nullable<int> skill_27 { get; set; }
        public Nullable<int> skill_28 { get; set; }
        public Nullable<int> skill_29 { get; set; }
        public Nullable<int> skill_30 { get; set; }
        public Nullable<int> skill_31 { get; set; }
        public Nullable<int> skill_32 { get; set; }
        public Nullable<int> skill_33 { get; set; }
        public Nullable<int> skill_34 { get; set; }
        public Nullable<int> skill_35 { get; set; }
        public Nullable<int> skill_36 { get; set; }
        public Nullable<int> skill_37 { get; set; }
        public Nullable<int> skill_38 { get; set; }
        public Nullable<int> skill_39 { get; set; }
        public Nullable<int> skill_40 { get; set; }
        public Nullable<int> skill_41 { get; set; }
        public Nullable<int> skill_42 { get; set; }
        public Nullable<int> skill_43 { get; set; }
        public Nullable<int> skill_44 { get; set; }
        public Nullable<int> skill_45 { get; set; }
        public Nullable<int> skill_46 { get; set; }
        public Nullable<int> skill_47 { get; set; }
        public Nullable<int> skill_48 { get; set; }
        public Nullable<int> skill_49 { get; set; }
        public Nullable<int> skill_50 { get; set; }
        public Nullable<int> skill_51 { get; set; }
        public Nullable<int> skill_52 { get; set; }
        public Nullable<int> skill_53 { get; set; }
        public Nullable<int> skill_54 { get; set; }
        public Nullable<int> skill_55 { get; set; }
        public Nullable<int> skill_56 { get; set; }
        public Nullable<int> skill_57 { get; set; }
        public Nullable<int> skill_58 { get; set; }
        public Nullable<int> skill_59 { get; set; }
        public Nullable<int> skill_60 { get; set; }
        public Nullable<int> skill_61 { get; set; }
        public Nullable<int> skill_62 { get; set; }
        public Nullable<int> skill_63 { get; set; }
        public Nullable<int> skill_64 { get; set; }
        public Nullable<int> skill_65 { get; set; }
        public Nullable<int> skill_66 { get; set; }
        public Nullable<int> skill_67 { get; set; }
        public Nullable<int> skill_68 { get; set; }
        public Nullable<int> skill_69 { get; set; }
        public Nullable<int> skill_70 { get; set; }
        public Nullable<int> skill_71 { get; set; }
        public Nullable<int> skill_72 { get; set; }
        public Nullable<int> skill_73 { get; set; }
    }
}
