//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class door
    {
        public int id { get; set; }
        public short doorid { get; set; }
        public string zone { get; set; }
        public int version { get; set; }
        public string name { get; set; }
        public float pos_y { get; set; }
        public float pos_x { get; set; }
        public float pos_z { get; set; }
        public float heading { get; set; }
        public short opentype { get; set; }
        public short guild { get; set; }
        public short lockpick { get; set; }
        public int keyitem { get; set; }
        public int keyitem2 { get; set; }
        public byte nokeyring { get; set; }
        public short triggerdoor { get; set; }
        public short triggertype { get; set; }
        public short doorisopen { get; set; }
        public int door_param { get; set; }
        public string dest_zone { get; set; }
        public long dest_instance { get; set; }
        public Nullable<float> dest_x { get; set; }
        public Nullable<float> dest_y { get; set; }
        public Nullable<float> dest_z { get; set; }
        public Nullable<float> dest_heading { get; set; }
        public Nullable<int> invert_state { get; set; }
        public Nullable<int> incline { get; set; }
        public int size { get; set; }
        public Nullable<float> buffer { get; set; }
        public long client_version_mask { get; set; }
        public byte is_ldon_door { get; set; }
        public sbyte disable_timer { get; set; }
    }
}
