//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class eqtime
    {
        public sbyte minute { get; set; }
        public sbyte hour { get; set; }
        public sbyte day { get; set; }
        public sbyte month { get; set; }
        public int year { get; set; }
        public int realtime { get; set; }
    }
}
