//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventlog
    {
        public long id { get; set; }
        public string accountname { get; set; }
        public Nullable<long> accountid { get; set; }
        public int status { get; set; }
        public string charname { get; set; }
        public string target { get; set; }
        public System.DateTime time { get; set; }
        public string descriptiontype { get; set; }
        public string description { get; set; }
        public int event_nid { get; set; }
    }
}
