//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class faction_list
    {
        public int id { get; set; }
        public string name { get; set; }
        public short @base { get; set; }
        public short mod_c1 { get; set; }
        public short mod_c2 { get; set; }
        public short mod_c3 { get; set; }
        public short mod_c4 { get; set; }
        public short mod_c5 { get; set; }
        public short mod_c6 { get; set; }
        public short mod_c7 { get; set; }
        public short mod_c8 { get; set; }
        public short mod_c9 { get; set; }
        public short mod_c10 { get; set; }
        public short mod_c11 { get; set; }
        public short mod_c12 { get; set; }
        public short mod_c13 { get; set; }
        public short mod_c14 { get; set; }
        public short mod_c15 { get; set; }
        public short mod_c16 { get; set; }
        public short mod_r1 { get; set; }
        public short mod_r2 { get; set; }
        public short mod_r3 { get; set; }
        public short mod_r4 { get; set; }
        public short mod_r5 { get; set; }
        public short mod_r6 { get; set; }
        public short mod_r7 { get; set; }
        public short mod_r8 { get; set; }
        public short mod_r9 { get; set; }
        public short mod_r10 { get; set; }
        public short mod_r11 { get; set; }
        public short mod_r12 { get; set; }
        public short mod_r14 { get; set; }
        public short mod_r60 { get; set; }
        public short mod_r75 { get; set; }
        public short mod_r108 { get; set; }
        public short mod_r120 { get; set; }
        public short mod_r128 { get; set; }
        public short mod_r130 { get; set; }
        public short mod_r161 { get; set; }
        public short mod_r330 { get; set; }
        public short mod_d140 { get; set; }
        public short mod_d201 { get; set; }
        public short mod_d202 { get; set; }
        public short mod_d203 { get; set; }
        public short mod_d204 { get; set; }
        public short mod_d205 { get; set; }
        public short mod_d206 { get; set; }
        public short mod_d207 { get; set; }
        public short mod_d208 { get; set; }
        public short mod_d209 { get; set; }
        public short mod_d210 { get; set; }
        public short mod_d211 { get; set; }
        public short mod_d212 { get; set; }
        public short mod_d213 { get; set; }
        public short mod_d214 { get; set; }
        public short mod_d215 { get; set; }
        public short mod_d216 { get; set; }
    }
}
