//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fear_hints
    {
        public int id { get; set; }
        public string zone { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public sbyte forced { get; set; }
        public sbyte disjoint { get; set; }
    }
}
