//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fishing
    {
        public int id { get; set; }
        public int zoneid { get; set; }
        public int Itemid { get; set; }
        public short skill_level { get; set; }
        public short chance { get; set; }
        public int npc_id { get; set; }
        public int npc_chance { get; set; }
    }
}
