//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ground_spawns
    {
        public long id { get; set; }
        public long zoneid { get; set; }
        public int version { get; set; }
        public float max_x { get; set; }
        public float max_y { get; set; }
        public float max_z { get; set; }
        public float min_x { get; set; }
        public float min_y { get; set; }
        public float heading { get; set; }
        public string name { get; set; }
        public long item { get; set; }
        public long max_allowed { get; set; }
        public string comment { get; set; }
        public decimal respawn_timer { get; set; }
    }
}
