//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_controllers
    {
        public int id { get; set; }
        public int npc_id { get; set; }
        public int owned_guild_id { get; set; }
        public int zoneid { get; set; }
        public string terrainarea { get; set; }
    }
}
