//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_members
    {
        public int char_id { get; set; }
        public int guild_id { get; set; }
        public byte rank { get; set; }
        public byte tribute_enable { get; set; }
        public long total_tribute { get; set; }
        public long last_tribute { get; set; }
        public byte banker { get; set; }
        public string public_note { get; set; }
        public byte alt { get; set; }
    }
}
