//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_bank
    {
        public long guildid { get; set; }
        public byte area { get; set; }
        public long slot { get; set; }
        public long itemid { get; set; }
        public long qty { get; set; }
        public string donator { get; set; }
        public byte permissions { get; set; }
        public string whofor { get; set; }
    }
}
