//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_ranks
    {
        public int guild_id { get; set; }
        public byte rank { get; set; }
        public string title { get; set; }
        public byte can_hear { get; set; }
        public byte can_speak { get; set; }
        public byte can_invite { get; set; }
        public byte can_remove { get; set; }
        public byte can_promote { get; set; }
        public byte can_demote { get; set; }
        public byte can_motd { get; set; }
        public byte can_warpeace { get; set; }
    }
}
