//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild
    {
        public int id { get; set; }
        public string name { get; set; }
        public int leader { get; set; }
        public short minstatus { get; set; }
        public string motd { get; set; }
        public long tribute { get; set; }
        public string motd_setter { get; set; }
        public string channel { get; set; }
        public string url { get; set; }
    }
}
