//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class hors
    {
        public string filename { get; set; }
        public short race { get; set; }
        public bool gender { get; set; }
        public sbyte texture { get; set; }
        public float mountspeed { get; set; }
        public string notes { get; set; }
    }
}
