//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_exemptions
    {
        public int exemption_id { get; set; }
        public string exemption_ip { get; set; }
        public Nullable<int> exemption_amount { get; set; }
    }
}
