//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_tick
    {
        public int it_itemid { get; set; }
        public int it_chance { get; set; }
        public int it_level { get; set; }
        public int it_id { get; set; }
        public string it_qglobal { get; set; }
        public sbyte it_bagslot { get; set; }
    }
}
