//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ldon_trap_templates
    {
        public long id { get; set; }
        public byte type { get; set; }
        public int spell_id { get; set; }
        public int skill { get; set; }
        public byte locked { get; set; }
    }
}
