//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class level_exp_mods
    {
        public int level { get; set; }
        public Nullable<float> exp_mod { get; set; }
        public Nullable<float> aa_exp_mod { get; set; }
    }
}
