//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lfguild
    {
        public byte type { get; set; }
        public string name { get; set; }
        public string comment { get; set; }
        public byte fromlevel { get; set; }
        public byte tolevel { get; set; }
        public long classes { get; set; }
        public long aacount { get; set; }
        public long timezone { get; set; }
        public long timeposted { get; set; }
    }
}
