//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_worldservers
    {
        public long id { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public long admin_id { get; set; }
        public bool greenname { get; set; }
        public sbyte showdown { get; set; }
        public sbyte chat { get; set; }
        public string note { get; set; }
    }
}
