//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_accounts
    {
        public long id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string ip { get; set; }
        public byte[] auth { get; set; }
        public byte lsadmin { get; set; }
        public byte lsstatus { get; set; }
        public byte worldadmin { get; set; }
        public byte user_active { get; set; }
        public int user_lastvisit { get; set; }
    }
}
