//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class logsys_categories
    {
        public int log_category_id { get; set; }
        public string log_category_description { get; set; }
        public Nullable<short> log_to_console { get; set; }
        public Nullable<short> log_to_file { get; set; }
        public Nullable<short> log_to_gmsay { get; set; }
    }
}
