//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class loottable
    {
        public long id { get; set; }
        public string name { get; set; }
        public long mincash { get; set; }
        public long maxcash { get; set; }
        public long avgcoin { get; set; }
        public sbyte done { get; set; }
    }
}
