//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lootdrop_entries
    {
        public long lootdrop_id { get; set; }
        public int item_id { get; set; }
        public int item_charges { get; set; }
        public byte equip_item { get; set; }
        public float chance { get; set; }
        public float disabled_chance { get; set; }
        public sbyte minlevel { get; set; }
        public sbyte maxlevel { get; set; }
        public byte multiplier { get; set; }
    }
}
