//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail
    {
        public long msgid { get; set; }
        public long charid { get; set; }
        public int timestamp { get; set; }
        public string from { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string to { get; set; }
        public sbyte status { get; set; }
    }
}
