//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc_buffs
    {
        public long MercBuffId { get; set; }
        public long MercId { get; set; }
        public long SpellId { get; set; }
        public long CasterLevel { get; set; }
        public long DurationFormula { get; set; }
        public int TicsRemaining { get; set; }
        public long PoisonCounters { get; set; }
        public long DiseaseCounters { get; set; }
        public long CurseCounters { get; set; }
        public long CorruptionCounters { get; set; }
        public long HitCount { get; set; }
        public long MeleeRune { get; set; }
        public long MagicRune { get; set; }
        public int dot_rune { get; set; }
        public int caston_x { get; set; }
        public bool Persistent { get; set; }
        public int caston_y { get; set; }
        public int caston_z { get; set; }
        public int ExtraDIChance { get; set; }
    
        public virtual merc merc { get; set; }
    }
}
