//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc_stats
    {
        public long merc_npc_type_id { get; set; }
        public byte clientlevel { get; set; }
        public byte level { get; set; }
        public int hp { get; set; }
        public int mana { get; set; }
        public short AC { get; set; }
        public int ATK { get; set; }
        public int STR { get; set; }
        public int STA { get; set; }
        public int DEX { get; set; }
        public int AGI { get; set; }
        public int C_INT { get; set; }
        public int WIS { get; set; }
        public int CHA { get; set; }
        public short MR { get; set; }
        public short CR { get; set; }
        public short DR { get; set; }
        public short FR { get; set; }
        public short PR { get; set; }
        public short Corrup { get; set; }
        public long mindmg { get; set; }
        public long maxdmg { get; set; }
        public short attack_count { get; set; }
        public sbyte attack_speed { get; set; }
        public byte attack_delay { get; set; }
        public string special_abilities { get; set; }
        public int Accuracy { get; set; }
        public long hp_regen_rate { get; set; }
        public long mana_regen_rate { get; set; }
        public float runspeed { get; set; }
        public int statscale { get; set; }
        public float spellscale { get; set; }
        public float healscale { get; set; }
    }
}
