//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc_spell_list_entries
    {
        public long merc_spell_list_entry_id { get; set; }
        public long merc_spell_list_id { get; set; }
        public long spell_id { get; set; }
        public long spell_type { get; set; }
        public byte stance_id { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public sbyte slot { get; set; }
        public byte procChance { get; set; }
    
        public virtual merc_spell_lists merc_spell_lists { get; set; }
    }
}
