//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc_armorinfo
    {
        public int id { get; set; }
        public long merc_npc_type_id { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public byte texture { get; set; }
        public byte helmtexture { get; set; }
        public long armortint_id { get; set; }
        public byte armortint_red { get; set; }
        public byte armortint_green { get; set; }
        public byte armortint_blue { get; set; }
    }
}
