//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc_weaponinfo
    {
        public int id { get; set; }
        public int merc_npc_type_id { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public int d_melee_texture1 { get; set; }
        public int d_melee_texture2 { get; set; }
        public byte prim_melee_type { get; set; }
        public byte sec_melee_type { get; set; }
    }
}
