//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public merc()
        {
            this.merc_buffs = new HashSet<merc_buffs>();
        }
    
        public long MercID { get; set; }
        public long OwnerCharacterID { get; set; }
        public bool Slot { get; set; }
        public string Name { get; set; }
        public long TemplateID { get; set; }
        public long SuspendedTime { get; set; }
        public bool IsSuspended { get; set; }
        public long TimerRemaining { get; set; }
        public byte Gender { get; set; }
        public float MercSize { get; set; }
        public byte StanceID { get; set; }
        public long HP { get; set; }
        public long Mana { get; set; }
        public long Endurance { get; set; }
        public long Face { get; set; }
        public long LuclinHairStyle { get; set; }
        public long LuclinHairColor { get; set; }
        public long LuclinEyeColor { get; set; }
        public long LuclinEyeColor2 { get; set; }
        public long LuclinBeardColor { get; set; }
        public long LuclinBeard { get; set; }
        public long DrakkinHeritage { get; set; }
        public long DrakkinTattoo { get; set; }
        public long DrakkinDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<merc_buffs> merc_buffs { get; set; }
    }
}
