//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchantlist
    {
        public int merchantid { get; set; }
        public int slot { get; set; }
        public int item { get; set; }
        public short faction_required { get; set; }
        public byte level_required { get; set; }
        public int alt_currency_cost { get; set; }
        public int classes_required { get; set; }
        public int probability { get; set; }
    }
}
