//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class axclassicEntities : DbContext
    {
        public axclassicEntities()
            : base("name=axclassicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aa_ability> aa_ability { get; set; }
        public virtual DbSet<aa_actions> aa_actions { get; set; }
        public virtual DbSet<aa_effects> aa_effects { get; set; }
        public virtual DbSet<aa_rank_effects> aa_rank_effects { get; set; }
        public virtual DbSet<aa_rank_prereqs> aa_rank_prereqs { get; set; }
        public virtual DbSet<aa_ranks> aa_ranks { get; set; }
        public virtual DbSet<aa_required_level_cost> aa_required_level_cost { get; set; }
        public virtual DbSet<aa_swarmpets> aa_swarmpets { get; set; }
        public virtual DbSet<aa_timers> aa_timers { get; set; }
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<account_flags> account_flags { get; set; }
        public virtual DbSet<activity> activities { get; set; }
        public virtual DbSet<adventure_details> adventure_details { get; set; }
        public virtual DbSet<adventure_members> adventure_members { get; set; }
        public virtual DbSet<adventure_stats> adventure_stats { get; set; }
        public virtual DbSet<adventure_template> adventure_template { get; set; }
        public virtual DbSet<adventure_template_entry> adventure_template_entry { get; set; }
        public virtual DbSet<adventure_template_entry_flavor> adventure_template_entry_flavor { get; set; }
        public virtual DbSet<altadv_vars> altadv_vars { get; set; }
        public virtual DbSet<alternate_currency> alternate_currency { get; set; }
        public virtual DbSet<banned_ips> banned_ips { get; set; }
        public virtual DbSet<base_data> base_data { get; set; }
        public virtual DbSet<blocked_spells> blocked_spells { get; set; }
        public virtual DbSet<bot_buffs> bot_buffs { get; set; }
        public virtual DbSet<bot_command_settings> bot_command_settings { get; set; }
        public virtual DbSet<bot_data> bot_data { get; set; }
        public virtual DbSet<bot_group_members> bot_group_members { get; set; }
        public virtual DbSet<bot_groups> bot_groups { get; set; }
        public virtual DbSet<bot_guild_members> bot_guild_members { get; set; }
        public virtual DbSet<bot_heal_rotation_members> bot_heal_rotation_members { get; set; }
        public virtual DbSet<bot_heal_rotation_targets> bot_heal_rotation_targets { get; set; }
        public virtual DbSet<bot_heal_rotations> bot_heal_rotations { get; set; }
        public virtual DbSet<bot_inspect_messages> bot_inspect_messages { get; set; }
        public virtual DbSet<bot_inventories> bot_inventories { get; set; }
        public virtual DbSet<bot_pet_buffs> bot_pet_buffs { get; set; }
        public virtual DbSet<bot_pet_inventories> bot_pet_inventories { get; set; }
        public virtual DbSet<bot_pets> bot_pets { get; set; }
        public virtual DbSet<bot_spell_casting_chances> bot_spell_casting_chances { get; set; }
        public virtual DbSet<bot_spells_entries> bot_spells_entries { get; set; }
        public virtual DbSet<bot_stances> bot_stances { get; set; }
        public virtual DbSet<bot_timers> bot_timers { get; set; }
        public virtual DbSet<botbuffs___> botbuffs___ { get; set; }
        public virtual DbSet<botgroup_old> botgroup_old { get; set; }
        public virtual DbSet<botgroupmembers_old> botgroupmembers_old { get; set; }
        public virtual DbSet<botguildmembers_old> botguildmembers_old { get; set; }
        public virtual DbSet<botinventory_old> botinventory_old { get; set; }
        public virtual DbSet<botpetbuffs_old> botpetbuffs_old { get; set; }
        public virtual DbSet<botpetinventory_old> botpetinventory_old { get; set; }
        public virtual DbSet<botpets_old> botpets_old { get; set; }
        public virtual DbSet<bots_old> bots_old { get; set; }
        public virtual DbSet<botstances_old> botstances_old { get; set; }
        public virtual DbSet<bottimers_old> bottimers_old { get; set; }
        public virtual DbSet<bug> bugs { get; set; }
        public virtual DbSet<buyer> buyers { get; set; }
        public virtual DbSet<char_create_combinations> char_create_combinations { get; set; }
        public virtual DbSet<char_create_point_allocations> char_create_point_allocations { get; set; }
        public virtual DbSet<char_recipe_list> char_recipe_list { get; set; }
        public virtual DbSet<character_activities> character_activities { get; set; }
        public virtual DbSet<character_alt_currency> character_alt_currency { get; set; }
        public virtual DbSet<character_alternate_abilities> character_alternate_abilities { get; set; }
        public virtual DbSet<character_alternate_abilities_old> character_alternate_abilities_old { get; set; }
        public virtual DbSet<character_backup> character_backup { get; set; }
        public virtual DbSet<character_bandolier> character_bandolier { get; set; }
        public virtual DbSet<character_bind> character_bind { get; set; }
        public virtual DbSet<character_buffs> character_buffs { get; set; }
        public virtual DbSet<character_corpse_items> character_corpse_items { get; set; }
        public virtual DbSet<character_corpses> character_corpses { get; set; }
        public virtual DbSet<character_currency> character_currency { get; set; }
        public virtual DbSet<character_data> character_data { get; set; }
        public virtual DbSet<character_data__> character_data__ { get; set; }
        public virtual DbSet<character_disciplines> character_disciplines { get; set; }
        public virtual DbSet<character_enabledtasks> character_enabledtasks { get; set; }
        public virtual DbSet<character_inspect_messages> character_inspect_messages { get; set; }
        public virtual DbSet<character_item_recast> character_item_recast { get; set; }
        public virtual DbSet<character_languages> character_languages { get; set; }
        public virtual DbSet<character_leadership_abilities> character_leadership_abilities { get; set; }
        public virtual DbSet<character_material> character_material { get; set; }
        public virtual DbSet<character_memmed_spells> character_memmed_spells { get; set; }
        public virtual DbSet<character_old> character_old { get; set; }
        public virtual DbSet<character_pet_buffs> character_pet_buffs { get; set; }
        public virtual DbSet<character_pet_info> character_pet_info { get; set; }
        public virtual DbSet<character_pet_inventory> character_pet_inventory { get; set; }
        public virtual DbSet<character_potionbelt> character_potionbelt { get; set; }
        public virtual DbSet<character_skills> character_skills { get; set; }
        public virtual DbSet<character_spells> character_spells { get; set; }
        public virtual DbSet<character_tasks> character_tasks { get; set; }
        public virtual DbSet<chatchannel> chatchannels { get; set; }
        public virtual DbSet<class_skill> class_skill { get; set; }
        public virtual DbSet<command_settings> command_settings { get; set; }
        public virtual DbSet<commands_old> commands_old { get; set; }
        public virtual DbSet<completed_tasks> completed_tasks { get; set; }
        public virtual DbSet<damageshieldtype> damageshieldtypes { get; set; }
        public virtual DbSet<db_str> db_str { get; set; }
        public virtual DbSet<discovered_items> discovered_items { get; set; }
        public virtual DbSet<door> doors { get; set; }
        public virtual DbSet<editor_values> editor_values { get; set; }
        public virtual DbSet<eqbnew> eqbnews { get; set; }
        public virtual DbSet<eventlog> eventlogs { get; set; }
        public virtual DbSet<faction_list> faction_list { get; set; }
        public virtual DbSet<faction_list_mod> faction_list_mod { get; set; }
        public virtual DbSet<faction_values> faction_values { get; set; }
        public virtual DbSet<fear_hints> fear_hints { get; set; }
        public virtual DbSet<fishing> fishings { get; set; }
        public virtual DbSet<forage> forages { get; set; }
        public virtual DbSet<friend> friends { get; set; }
        public virtual DbSet<goallist> goallists { get; set; }
        public virtual DbSet<graveyard> graveyards { get; set; }
        public virtual DbSet<grid> grids { get; set; }
        public virtual DbSet<grid_entries> grid_entries { get; set; }
        public virtual DbSet<ground_spawns> ground_spawns { get; set; }
        public virtual DbSet<group_id> group_id { get; set; }
        public virtual DbSet<group_leaders> group_leaders { get; set; }
        public virtual DbSet<group_leaders__> group_leaders__ { get; set; }
        public virtual DbSet<guild_alliances> guild_alliances { get; set; }
        public virtual DbSet<guild_controllers> guild_controllers { get; set; }
        public virtual DbSet<guild_ranks> guild_ranks { get; set; }
        public virtual DbSet<guild_relations> guild_relations { get; set; }
        public virtual DbSet<guild> guilds { get; set; }
        public virtual DbSet<hacker> hackers { get; set; }
        public virtual DbSet<hors> horses { get; set; }
        public virtual DbSet<instance_list> instance_list { get; set; }
        public virtual DbSet<instance_list_player> instance_list_player { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<inventory_snapshots> inventory_snapshots { get; set; }
        public virtual DbSet<ip_exemptions> ip_exemptions { get; set; }
        public virtual DbSet<item_tick> item_tick { get; set; }
        public virtual DbSet<launcher> launchers { get; set; }
        public virtual DbSet<launcher_zones> launcher_zones { get; set; }
        public virtual DbSet<ldon_trap_entries> ldon_trap_entries { get; set; }
        public virtual DbSet<ldon_trap_templates> ldon_trap_templates { get; set; }
        public virtual DbSet<level_exp_mods> level_exp_mods { get; set; }
        public virtual DbSet<lfguild> lfguilds { get; set; }
        public virtual DbSet<login_accounts> login_accounts { get; set; }
        public virtual DbSet<login_authchange> login_authchange { get; set; }
        public virtual DbSet<login_worldservers> login_worldservers { get; set; }
        public virtual DbSet<logsys_categories> logsys_categories { get; set; }
        public virtual DbSet<lootdrop> lootdrops { get; set; }
        public virtual DbSet<lootdrop_entries> lootdrop_entries { get; set; }
        public virtual DbSet<loottable> loottables { get; set; }
        public virtual DbSet<loottable_entries> loottable_entries { get; set; }
        public virtual DbSet<mail> mails { get; set; }
        public virtual DbSet<merc_armorinfo> merc_armorinfo { get; set; }
        public virtual DbSet<merc_buffs> merc_buffs { get; set; }
        public virtual DbSet<merc_spell_list_entries> merc_spell_list_entries { get; set; }
        public virtual DbSet<merc_spell_lists> merc_spell_lists { get; set; }
        public virtual DbSet<merc_stats> merc_stats { get; set; }
        public virtual DbSet<merc_weaponinfo> merc_weaponinfo { get; set; }
        public virtual DbSet<merchantlist> merchantlists { get; set; }
        public virtual DbSet<merchantlist_temp> merchantlist_temp { get; set; }
        public virtual DbSet<merchantset> merchantsets { get; set; }
        public virtual DbSet<merc> mercs { get; set; }
        public virtual DbSet<name_filter> name_filter { get; set; }
        public virtual DbSet<npc_emotes> npc_emotes { get; set; }
        public virtual DbSet<npc_faction> npc_faction { get; set; }
        public virtual DbSet<npc_faction_entries> npc_faction_entries { get; set; }
        public virtual DbSet<npc_spells> npc_spells { get; set; }
        public virtual DbSet<npc_spells_effects> npc_spells_effects { get; set; }
        public virtual DbSet<npc_spells_effects_entries> npc_spells_effects_entries { get; set; }
        public virtual DbSet<npc_spells_entries> npc_spells_entries { get; set; }
        public virtual DbSet<npc_types> npc_types { get; set; }
        public virtual DbSet<npc_types_metadata> npc_types_metadata { get; set; }
        public virtual DbSet<npc_types_tint> npc_types_tint { get; set; }
        public virtual DbSet<@object> objects { get; set; }
        public virtual DbSet<object_contents> object_contents { get; set; }
        public virtual DbSet<peq_admin> peq_admin { get; set; }
        public virtual DbSet<perl_event_export_settings> perl_event_export_settings { get; set; }
        public virtual DbSet<petition> petitions { get; set; }
        public virtual DbSet<pet> pets { get; set; }
        public virtual DbSet<pets__> pets__ { get; set; }
        public virtual DbSet<player_corpses_backup> player_corpses_backup { get; set; }
        public virtual DbSet<player_titlesets> player_titlesets { get; set; }
        public virtual DbSet<proximity> proximities { get; set; }
        public virtual DbSet<qed_admin> qed_admin { get; set; }
        public virtual DbSet<qed_zone> qed_zone { get; set; }
        public virtual DbSet<qs_merchant_transaction_record> qs_merchant_transaction_record { get; set; }
        public virtual DbSet<qs_player_aa_rate_hourly> qs_player_aa_rate_hourly { get; set; }
        public virtual DbSet<qs_player_delete_record> qs_player_delete_record { get; set; }
        public virtual DbSet<qs_player_events> qs_player_events { get; set; }
        public virtual DbSet<qs_player_handin_record> qs_player_handin_record { get; set; }
        public virtual DbSet<qs_player_move_record> qs_player_move_record { get; set; }
        public virtual DbSet<qs_player_npc_kill_record> qs_player_npc_kill_record { get; set; }
        public virtual DbSet<qs_player_speech> qs_player_speech { get; set; }
        public virtual DbSet<qs_player_trade_record> qs_player_trade_record { get; set; }
        public virtual DbSet<quest_globals> quest_globals { get; set; }
        public virtual DbSet<quest_items> quest_items { get; set; }
        public virtual DbSet<race> races { get; set; }
        public virtual DbSet<raid_details> raid_details { get; set; }
        public virtual DbSet<raid_groups> raid_groups { get; set; }
        public virtual DbSet<raid_leader> raid_leader { get; set; }
        public virtual DbSet<raid_members> raid_members { get; set; }
        public virtual DbSet<raid_ungrouped_members> raid_ungrouped_members { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<respawn_times> respawn_times { get; set; }
        public virtual DbSet<rule_sets> rule_sets { get; set; }
        public virtual DbSet<rule_values> rule_values { get; set; }
        public virtual DbSet<saylink> saylinks { get; set; }
        public virtual DbSet<skill_caps> skill_caps { get; set; }
        public virtual DbSet<spawn_conditions> spawn_conditions { get; set; }
        public virtual DbSet<spawn_events> spawn_events { get; set; }
        public virtual DbSet<spawn2> spawn2 { get; set; }
        public virtual DbSet<spawnentry> spawnentries { get; set; }
        public virtual DbSet<spawngroup> spawngroups { get; set; }
        public virtual DbSet<spells_new> spells_new { get; set; }
        public virtual DbSet<start_zones> start_zones { get; set; }
        public virtual DbSet<starting_items> starting_items { get; set; }
        public virtual DbSet<starting_items___> starting_items___ { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<taskset> tasksets { get; set; }
        public virtual DbSet<taunt_flags> taunt_flags { get; set; }
        public virtual DbSet<tblloginserveraccount> tblloginserveraccounts { get; set; }
        public virtual DbSet<tblserveradminregistration> tblserveradminregistrations { get; set; }
        public virtual DbSet<tblserverlisttype> tblserverlisttypes { get; set; }
        public virtual DbSet<tblworldserverregistration> tblworldserverregistrations { get; set; }
        public virtual DbSet<timer> timers { get; set; }
        public virtual DbSet<title> titles { get; set; }
        public virtual DbSet<trader> traders { get; set; }
        public virtual DbSet<tradeskill_recipe> tradeskill_recipe { get; set; }
        public virtual DbSet<tradeskill_recipe_entries> tradeskill_recipe_entries { get; set; }
        public virtual DbSet<trap> traps { get; set; }
        public virtual DbSet<tribute_levels> tribute_levels { get; set; }
        public virtual DbSet<tribute> tributes { get; set; }
        public virtual DbSet<variable> variables { get; set; }
        public virtual DbSet<zone> zones { get; set; }
        public virtual DbSet<zone___> zone___ { get; set; }
        public virtual DbSet<zone_flags> zone_flags { get; set; }
        public virtual DbSet<zone_points> zone_points { get; set; }
        public virtual DbSet<zone_server> zone_server { get; set; }
        public virtual DbSet<zone_state_dump> zone_state_dump { get; set; }
        public virtual DbSet<zoneserver_auth> zoneserver_auth { get; set; }
        public virtual DbSet<account_ip> account_ip { get; set; }
        public virtual DbSet<account_rewards> account_rewards { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<botbuffs_old> botbuffs_old { get; set; }
        public virtual DbSet<character_tribute> character_tribute { get; set; }
        public virtual DbSet<core_version> core_version { get; set; }
        public virtual DbSet<eqtime> eqtimes { get; set; }
        public virtual DbSet<gm_ips> gm_ips { get; set; }
        public virtual DbSet<guild_bank> guild_bank { get; set; }
        public virtual DbSet<guild_members> guild_members { get; set; }
        public virtual DbSet<inventory_version> inventory_version { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<keyring> keyrings { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<qed_quests> qed_quests { get; set; }
        public virtual DbSet<raid_leaders> raid_leaders { get; set; }
        public virtual DbSet<sharedbank> sharedbanks { get; set; }
        public virtual DbSet<spawn_condition_values> spawn_condition_values { get; set; }
        public virtual DbSet<spell> spells { get; set; }
        public virtual DbSet<trader_audit> trader_audit { get; set; }
        public virtual DbSet<veteran_reward_templates> veteran_reward_templates { get; set; }
        public virtual DbSet<vspawnloc> vspawnlocs { get; set; }
        public virtual DbSet<vw_bot_character_mobs> vw_bot_character_mobs { get; set; }
        public virtual DbSet<vw_bot_groups> vw_bot_groups { get; set; }
        public virtual DbSet<vw_groups> vw_groups { get; set; }
        public virtual DbSet<vw_guild_members> vw_guild_members { get; set; }
    }
}
