//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_faction_entries
    {
        public long npc_faction_id { get; set; }
        public long faction_id { get; set; }
        public int value { get; set; }
        public sbyte npc_value { get; set; }
        public sbyte temp { get; set; }
    }
}
