//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_spells
    {
        public long id { get; set; }
        public string name { get; set; }
        public long parent_list { get; set; }
        public short attack_proc { get; set; }
        public sbyte proc_chance { get; set; }
        public short range_proc { get; set; }
        public short rproc_chance { get; set; }
        public short defensive_proc { get; set; }
        public short dproc_chance { get; set; }
        public long fail_recast { get; set; }
        public long engaged_no_sp_recast_min { get; set; }
        public long engaged_no_sp_recast_max { get; set; }
        public byte engaged_b_self_chance { get; set; }
        public byte engaged_b_other_chance { get; set; }
        public byte engaged_d_chance { get; set; }
        public long pursue_no_sp_recast_min { get; set; }
        public long pursue_no_sp_recast_max { get; set; }
        public byte pursue_d_chance { get; set; }
        public long idle_no_sp_recast_min { get; set; }
        public long idle_no_sp_recast_max { get; set; }
        public byte idle_b_chance { get; set; }
    }
}
