//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_spells_effects_entries
    {
        public long id { get; set; }
        public int npc_spells_effects_id { get; set; }
        public short spell_effect_id { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public int se_base { get; set; }
        public int se_limit { get; set; }
        public int se_max { get; set; }
    }
}
