//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_types_metadata
    {
        public int npc_types_id { get; set; }
        public sbyte isPKMob { get; set; }
        public sbyte isNamedMob { get; set; }
        public sbyte isRaidTarget { get; set; }
        public sbyte isCreatedMob { get; set; }
        public sbyte isCustomFeatureNPC { get; set; }
    }
}
