//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_emotes
    {
        public int id { get; set; }
        public long emoteid { get; set; }
        public sbyte event_ { get; set; }
        public sbyte type { get; set; }
        public string text { get; set; }
    }
}
