//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_faction
    {
        public int id { get; set; }
        public string name { get; set; }
        public int primaryfaction { get; set; }
        public sbyte ignore_primary_assist { get; set; }
    }
}
