//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_types
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public byte level { get; set; }
        public int race { get; set; }
        public byte @class { get; set; }
        public int bodytype { get; set; }
        public int hp { get; set; }
        public int mana { get; set; }
        public byte gender { get; set; }
        public byte texture { get; set; }
        public byte helmtexture { get; set; }
        public int herosforgemodel { get; set; }
        public float size { get; set; }
        public long hp_regen_rate { get; set; }
        public long mana_regen_rate { get; set; }
        public long loottable_id { get; set; }
        public long merchant_id { get; set; }
        public long alt_currency_id { get; set; }
        public long npc_spells_id { get; set; }
        public long npc_spells_effects_id { get; set; }
        public int npc_faction_id { get; set; }
        public long adventure_template_id { get; set; }
        public Nullable<long> trap_template { get; set; }
        public long mindmg { get; set; }
        public long maxdmg { get; set; }
        public short attack_count { get; set; }
        public string npcspecialattks { get; set; }
        public string special_abilities { get; set; }
        public long aggroradius { get; set; }
        public long assistradius { get; set; }
        public long face { get; set; }
        public long luclin_hairstyle { get; set; }
        public long luclin_haircolor { get; set; }
        public long luclin_eyecolor { get; set; }
        public long luclin_eyecolor2 { get; set; }
        public long luclin_beardcolor { get; set; }
        public long luclin_beard { get; set; }
        public int drakkin_heritage { get; set; }
        public int drakkin_tattoo { get; set; }
        public int drakkin_details { get; set; }
        public long armortint_id { get; set; }
        public byte armortint_red { get; set; }
        public byte armortint_green { get; set; }
        public byte armortint_blue { get; set; }
        public int d_melee_texture1 { get; set; }
        public int d_melee_texture2 { get; set; }
        public string ammo_idfile { get; set; }
        public byte prim_melee_type { get; set; }
        public byte sec_melee_type { get; set; }
        public byte ranged_type { get; set; }
        public float runspeed { get; set; }
        public short MR { get; set; }
        public short CR { get; set; }
        public short DR { get; set; }
        public short FR { get; set; }
        public short PR { get; set; }
        public short Corrup { get; set; }
        public int PhR { get; set; }
        public short see_invis { get; set; }
        public short see_invis_undead { get; set; }
        public long qglobal { get; set; }
        public short AC { get; set; }
        public sbyte npc_aggro { get; set; }
        public sbyte spawn_limit { get; set; }
        public float attack_speed { get; set; }
        public byte attack_delay { get; set; }
        public sbyte findable { get; set; }
        public int STR { get; set; }
        public int STA { get; set; }
        public int DEX { get; set; }
        public int AGI { get; set; }
        public int C_INT { get; set; }
        public int WIS { get; set; }
        public int CHA { get; set; }
        public sbyte see_hide { get; set; }
        public sbyte see_improved_hide { get; set; }
        public sbyte trackable { get; set; }
        public sbyte isbot { get; set; }
        public sbyte exclude { get; set; }
        public int ATK { get; set; }
        public int Accuracy { get; set; }
        public int Avoidance { get; set; }
        public short slow_mitigation { get; set; }
        public int version { get; set; }
        public sbyte maxlevel { get; set; }
        public int scalerate { get; set; }
        public byte private_corpse { get; set; }
        public byte unique_spawn_by_name { get; set; }
        public byte underwater { get; set; }
        public sbyte isquest { get; set; }
        public long emoteid { get; set; }
        public float spellscale { get; set; }
        public float healscale { get; set; }
        public byte no_target_hotkey { get; set; }
        public byte raid_target { get; set; }
        public sbyte armtexture { get; set; }
        public sbyte bracertexture { get; set; }
        public sbyte handtexture { get; set; }
        public sbyte legtexture { get; set; }
        public sbyte feettexture { get; set; }
        public sbyte light { get; set; }
        public sbyte walkspeed { get; set; }
        public int peqid { get; set; }
        public sbyte unique_ { get; set; }
        public sbyte @fixed { get; set; }
        public sbyte ignore_despawn { get; set; }
    }
}
