//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_types_tint
    {
        public long id { get; set; }
        public string tint_set_name { get; set; }
        public byte red1h { get; set; }
        public byte grn1h { get; set; }
        public byte blu1h { get; set; }
        public byte red2c { get; set; }
        public byte grn2c { get; set; }
        public byte blu2c { get; set; }
        public byte red3a { get; set; }
        public byte grn3a { get; set; }
        public byte blu3a { get; set; }
        public byte red4b { get; set; }
        public byte grn4b { get; set; }
        public byte blu4b { get; set; }
        public byte red5g { get; set; }
        public byte grn5g { get; set; }
        public byte blu5g { get; set; }
        public byte red6l { get; set; }
        public byte grn6l { get; set; }
        public byte blu6l { get; set; }
        public byte red7f { get; set; }
        public byte grn7f { get; set; }
        public byte blu7f { get; set; }
        public byte red8x { get; set; }
        public byte grn8x { get; set; }
        public byte blu8x { get; set; }
        public byte red9x { get; set; }
        public byte grn9x { get; set; }
        public byte blu9x { get; set; }
    }
}
