//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_spells_entries
    {
        public long id { get; set; }
        public int npc_spells_id { get; set; }
        public short spellid { get; set; }
        public int type { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public short manacost { get; set; }
        public int recast_delay { get; set; }
        public short priority { get; set; }
        public Nullable<int> resist_adjust { get; set; }
    }
}
