//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class object_contents
    {
        public long zoneid { get; set; }
        public long parentid { get; set; }
        public long bagidx { get; set; }
        public long itemid { get; set; }
        public sbyte charges { get; set; }
        public System.DateTime droptime { get; set; }
        public Nullable<int> augslot1 { get; set; }
        public Nullable<int> augslot2 { get; set; }
        public Nullable<int> augslot3 { get; set; }
        public Nullable<int> augslot4 { get; set; }
        public Nullable<int> augslot5 { get; set; }
        public int augslot6 { get; set; }
    }
}
