//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class @object
    {
        public int id { get; set; }
        public long zoneid { get; set; }
        public int version { get; set; }
        public float xpos { get; set; }
        public float ypos { get; set; }
        public float zpos { get; set; }
        public float heading { get; set; }
        public int itemid { get; set; }
        public byte charges { get; set; }
        public string objectname { get; set; }
        public int type { get; set; }
        public int icon { get; set; }
        public int unknown08 { get; set; }
        public int unknown10 { get; set; }
        public int unknown20 { get; set; }
        public int unknown24 { get; set; }
        public int unknown60 { get; set; }
        public int unknown64 { get; set; }
        public int unknown68 { get; set; }
        public int unknown72 { get; set; }
        public int unknown76 { get; set; }
        public int unknown84 { get; set; }
        public float size { get; set; }
        public float tilt_x { get; set; }
        public float tilt_y { get; set; }
        public string display_name { get; set; }
    }
}
