//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pet
    {
        public string type { get; set; }
        public int petpower { get; set; }
        public int npcID { get; set; }
        public sbyte temp { get; set; }
        public sbyte petcontrol { get; set; }
        public sbyte petnaming { get; set; }
        public sbyte monsterflag { get; set; }
        public int equipmentset { get; set; }
    }
}
