//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class petition
    {
        public long dib { get; set; }
        public long petid { get; set; }
        public string charname { get; set; }
        public string accountname { get; set; }
        public string lastgm { get; set; }
        public string petitiontext { get; set; }
        public string gmtext { get; set; }
        public string zone { get; set; }
        public int urgency { get; set; }
        public int charclass { get; set; }
        public int charrace { get; set; }
        public int charlevel { get; set; }
        public int checkouts { get; set; }
        public int unavailables { get; set; }
        public sbyte ischeckedout { get; set; }
        public long senttime { get; set; }
    }
}
