//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class player_corpses_backup
    {
        public long id { get; set; }
        public long charid { get; set; }
        public long parent_corpse_id { get; set; }
        public short zoneid { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float heading { get; set; }
        public byte[] data { get; set; }
        public System.DateTime timeofdeath { get; set; }
        public System.DateTime timeofdelete { get; set; }
    }
}
