//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class proximity
    {
        public long zoneid { get; set; }
        public long exploreid { get; set; }
        public float minx { get; set; }
        public float maxx { get; set; }
        public float miny { get; set; }
        public float maxy { get; set; }
        public float minz { get; set; }
        public float maxz { get; set; }
    }
}
