//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qed_quests
    {
        public int quest_id { get; set; }
        public string quest_name { get; set; }
        public int startzone_id { get; set; }
        public int questgiver_npcid { get; set; }
        public int quest_status { get; set; }
        public string quest_developer { get; set; }
        public System.DateTime last_modified { get; set; }
    }
}
