//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_merchant_transaction_record
    {
        public int transaction_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> zone_id { get; set; }
        public Nullable<int> merchant_id { get; set; }
        public Nullable<int> merchant_pp { get; set; }
        public Nullable<int> merchant_gp { get; set; }
        public Nullable<int> merchant_sp { get; set; }
        public Nullable<int> merchant_cp { get; set; }
        public Nullable<int> merchant_items { get; set; }
        public Nullable<int> char_id { get; set; }
        public Nullable<int> char_pp { get; set; }
        public Nullable<int> char_gp { get; set; }
        public Nullable<int> char_sp { get; set; }
        public Nullable<int> char_cp { get; set; }
        public Nullable<int> char_items { get; set; }
    }
}
