//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_player_trade_record
    {
        public int trade_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> char1_id { get; set; }
        public Nullable<int> char1_pp { get; set; }
        public Nullable<int> char1_gp { get; set; }
        public Nullable<int> char1_sp { get; set; }
        public Nullable<int> char1_cp { get; set; }
        public Nullable<int> char1_items { get; set; }
        public Nullable<int> char2_id { get; set; }
        public Nullable<int> char2_pp { get; set; }
        public Nullable<int> char2_gp { get; set; }
        public Nullable<int> char2_sp { get; set; }
        public Nullable<int> char2_cp { get; set; }
        public Nullable<int> char2_items { get; set; }
    }
}
