//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_player_speech
    {
        public int id { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string message { get; set; }
        public short minstatus { get; set; }
        public int guilddbid { get; set; }
        public sbyte type { get; set; }
        public System.DateTime timerecorded { get; set; }
    }
}
