//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_player_handin_record
    {
        public int handin_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> quest_id { get; set; }
        public Nullable<int> char_id { get; set; }
        public Nullable<int> char_pp { get; set; }
        public Nullable<int> char_gp { get; set; }
        public Nullable<int> char_sp { get; set; }
        public Nullable<int> char_cp { get; set; }
        public Nullable<int> char_items { get; set; }
        public Nullable<int> npc_id { get; set; }
        public Nullable<int> npc_pp { get; set; }
        public Nullable<int> npc_gp { get; set; }
        public Nullable<int> npc_sp { get; set; }
        public Nullable<int> npc_cp { get; set; }
        public Nullable<int> npc_items { get; set; }
    }
}
