//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_player_npc_kill_record
    {
        public int fight_id { get; set; }
        public Nullable<int> npc_id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> zone_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
