//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class qs_player_delete_record
    {
        public int delete_id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> char_id { get; set; }
        public Nullable<int> stack_size { get; set; }
        public Nullable<int> char_items { get; set; }
    }
}
