//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_items
    {
        public int item_id { get; set; }
        public string npc { get; set; }
        public string zone { get; set; }
        public sbyte rewarded { get; set; }
        public sbyte handed { get; set; }
    }
}
