//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_globals
    {
        public int charid { get; set; }
        public int npcid { get; set; }
        public int zoneid { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public Nullable<int> expdate { get; set; }
    }
}
