//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class raid_leaders
    {
        public long gid { get; set; }
        public long rid { get; set; }
        public string marknpc { get; set; }
        public string maintank { get; set; }
        public string assist { get; set; }
        public string puller { get; set; }
        public byte[] leadershipaa { get; set; }
        public string mentoree { get; set; }
        public int mentor_percent { get; set; }
    }
}
