//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class raid_members
    {
        public int raidid { get; set; }
        public int charid { get; set; }
        public long groupid { get; set; }
        public int C_class { get; set; }
        public int level { get; set; }
        public string name { get; set; }
        public bool isgroupleader { get; set; }
        public bool israidleader { get; set; }
        public bool islooter { get; set; }
    }
}
