//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class rule_values
    {
        public byte ruleset_id { get; set; }
        public string rule_name { get; set; }
        public string rule_value { get; set; }
        public string notes { get; set; }
    }
}
