//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sharedbank
    {
        public Nullable<long> acctid { get; set; }
        public Nullable<int> slotid { get; set; }
        public Nullable<long> itemid { get; set; }
        public Nullable<int> charges { get; set; }
        public int augslot1 { get; set; }
        public int augslot2 { get; set; }
        public int augslot3 { get; set; }
        public int augslot4 { get; set; }
        public int augslot5 { get; set; }
        public int augslot6 { get; set; }
        public string custom_data { get; set; }
    }
}
