//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spawn2
    {
        public int id { get; set; }
        public int spawngroupID { get; set; }
        public string zone { get; set; }
        public int version { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float heading { get; set; }
        public int respawntime { get; set; }
        public int variance { get; set; }
        public int pathgrid { get; set; }
        public int C_condition { get; set; }
        public int cond_value { get; set; }
        public byte enabled { get; set; }
        public byte animation { get; set; }
    }
}
