//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spawn_events
    {
        public long id { get; set; }
        public string zone { get; set; }
        public int cond_id { get; set; }
        public string name { get; set; }
        public long period { get; set; }
        public byte next_minute { get; set; }
        public byte next_hour { get; set; }
        public byte next_day { get; set; }
        public byte next_month { get; set; }
        public long next_year { get; set; }
        public sbyte enabled { get; set; }
        public byte action { get; set; }
        public int argument { get; set; }
        public sbyte strict { get; set; }
    }
}
