//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spawn_conditions
    {
        public string zone { get; set; }
        public int id { get; set; }
        public int value { get; set; }
        public byte onchange { get; set; }
        public string name { get; set; }
    }
}
