//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spawngroup
    {
        public int id { get; set; }
        public string name { get; set; }
        public sbyte spawn_limit { get; set; }
        public float dist { get; set; }
        public float max_x { get; set; }
        public float min_x { get; set; }
        public float max_y { get; set; }
        public float min_y { get; set; }
        public int delay { get; set; }
        public int mindelay { get; set; }
        public sbyte despawn { get; set; }
        public int despawn_timer { get; set; }
    }
}
