//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spawn_condition_values
    {
        public long id { get; set; }
        public Nullable<byte> value { get; set; }
        public string zone { get; set; }
        public long instance_id { get; set; }
    }
}
