//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell
    {
        public int spellid { get; set; }
        public string name { get; set; }
        public string castonyou { get; set; }
        public string castonother { get; set; }
        public string fading { get; set; }
        public int range { get; set; }
        public int aoerange { get; set; }
        public int mana { get; set; }
        public int casttime { get; set; }
        public int recoverytime { get; set; }
        public int recasttime { get; set; }
        public int buffformula { get; set; }
        public int buffduration { get; set; }
        public int aoeduration { get; set; }
        public int targettype { get; set; }
        public string petname { get; set; }
        public int resist { get; set; }
        public int resist_adjust { get; set; }
        public int skill { get; set; }
        public int buff1 { get; set; }
        public int buff1val { get; set; }
        public int buff2 { get; set; }
        public int buff2val { get; set; }
        public int buff3 { get; set; }
        public int buff3val { get; set; }
        public int buff4 { get; set; }
        public int buff4val { get; set; }
        public int buff5 { get; set; }
        public int buff5val { get; set; }
        public int buff6 { get; set; }
        public int buff6val { get; set; }
        public int buff7 { get; set; }
        public int buff7val { get; set; }
        public int buff8 { get; set; }
        public int buff8val { get; set; }
        public int buff9 { get; set; }
        public int buff9val { get; set; }
        public int buff10 { get; set; }
        public int buff10val { get; set; }
        public int buff11 { get; set; }
        public int buff11val { get; set; }
        public int buff12 { get; set; }
        public int buff12val { get; set; }
        public int buff1form { get; set; }
        public int buff2form { get; set; }
        public int buff3form { get; set; }
        public int buff4form { get; set; }
        public int buff5form { get; set; }
        public int buff6form { get; set; }
        public int buff7form { get; set; }
        public int buff8form { get; set; }
        public int buff9form { get; set; }
        public int buff10form { get; set; }
        public int buff11form { get; set; }
        public int buff12form { get; set; }
        public int buff1max { get; set; }
        public int buff2max { get; set; }
        public int buff3max { get; set; }
        public int buff4max { get; set; }
        public int buff5max { get; set; }
        public int buff6max { get; set; }
        public int buff7max { get; set; }
        public int buff8max { get; set; }
        public int buff9max { get; set; }
        public int buff10max { get; set; }
        public int buff11max { get; set; }
        public int buff12max { get; set; }
        public int level1 { get; set; }
        public int level2 { get; set; }
        public int level3 { get; set; }
        public int level4 { get; set; }
        public int level5 { get; set; }
        public int level6 { get; set; }
        public int level7 { get; set; }
        public int level8 { get; set; }
        public int level9 { get; set; }
        public int level10 { get; set; }
        public int level11 { get; set; }
        public int level12 { get; set; }
        public int level13 { get; set; }
        public int level14 { get; set; }
        public int level15 { get; set; }
        public int level16 { get; set; }
        public int regent1_id { get; set; }
        public int regent1_count { get; set; }
        public int regent2_id { get; set; }
        public int regent2_count { get; set; }
        public int regent3_id { get; set; }
        public int regent3_count { get; set; }
        public int regent4_id { get; set; }
        public int regent4_count { get; set; }
        public int timeofday { get; set; }
    }
}
