//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class start_zones
    {
        public long id { get; set; }
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }
        public float heading { get; set; }
        public int zone_id { get; set; }
        public int bind_id { get; set; }
        public int player_choice { get; set; }
        public int player_class { get; set; }
        public int player_deity { get; set; }
        public int player_race { get; set; }
        public int start_zone { get; set; }
        public float bind_x { get; set; }
        public float bind_y { get; set; }
        public float bind_z { get; set; }
        public byte select_rank { get; set; }
    }
}
