//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class starting_items___
    {
        public long id { get; set; }
        public int race { get; set; }
        public int @class { get; set; }
        public int deityid { get; set; }
        public int zoneid { get; set; }
        public int itemid { get; set; }
        public byte item_charges { get; set; }
        public bool gm { get; set; }
        public int slot { get; set; }
    }
}
