//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public long id { get; set; }
        public long duration { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string reward { get; set; }
        public long rewardid { get; set; }
        public long cashreward { get; set; }
        public long xpreward { get; set; }
        public byte rewardmethod { get; set; }
        public int startzone { get; set; }
        public byte minlevel { get; set; }
        public byte maxlevel { get; set; }
        public bool repeatable { get; set; }
    }
}
