//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblloginserveraccount
    {
        public long LoginServerID { get; set; }
        public string AccountName { get; set; }
        public string AccountPassword { get; set; }
        public System.DateTime AccountCreateDate { get; set; }
        public string AccountEmail { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string LastIPAddress { get; set; }
        public sbyte FirstFlag { get; set; }
    }
}
