//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblworldserverregistration
    {
        public long ServerID { get; set; }
        public string ServerLongName { get; set; }
        public string ServerTagDescription { get; set; }
        public string ServerShortName { get; set; }
        public int ServerListTypeID { get; set; }
        public Nullable<System.DateTime> ServerLastLoginDate { get; set; }
        public string ServerLastIPAddr { get; set; }
        public int ServerAdminID { get; set; }
        public int ServerTrusted { get; set; }
        public string Note { get; set; }
    }
}
