//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class timer
    {
        public int char_id { get; set; }
        public int type { get; set; }
        public long start { get; set; }
        public long duration { get; set; }
        public sbyte enable { get; set; }
    }
}
