//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class title
    {
        public long id { get; set; }
        public sbyte skill_id { get; set; }
        public int min_skill_value { get; set; }
        public int max_skill_value { get; set; }
        public int min_aa_points { get; set; }
        public int max_aa_points { get; set; }
        public sbyte @class { get; set; }
        public bool gender { get; set; }
        public int char_id { get; set; }
        public int status { get; set; }
        public int item_id { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public int title_set { get; set; }
    }
}
