//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class trader_audit
    {
        public System.DateTime time { get; set; }
        public string seller { get; set; }
        public string buyer { get; set; }
        public string itemname { get; set; }
        public int quantity { get; set; }
        public int totalcost { get; set; }
        public sbyte trantype { get; set; }
    }
}
