//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class trader
    {
        public long char_id { get; set; }
        public long item_id { get; set; }
        public long serialnumber { get; set; }
        public int charges { get; set; }
        public long item_cost { get; set; }
        public byte slot_id { get; set; }
    }
}
