//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tradeskill_recipe_entries
    {
        public int id { get; set; }
        public int recipe_id { get; set; }
        public int item_id { get; set; }
        public sbyte successcount { get; set; }
        public sbyte failcount { get; set; }
        public sbyte componentcount { get; set; }
        public sbyte salvagecount { get; set; }
        public bool iscontainer { get; set; }
    }
}
