//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tradeskill_recipe
    {
        public int id { get; set; }
        public string name { get; set; }
        public short tradeskill { get; set; }
        public short skillneeded { get; set; }
        public short trivial { get; set; }
        public bool nofail { get; set; }
        public bool replace_container { get; set; }
        public string notes { get; set; }
        public bool enabled { get; set; }
        public sbyte must_learn { get; set; }
        public bool quest { get; set; }
    }
}
