//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class trap
    {
        public int id { get; set; }
        public string zone { get; set; }
        public int version { get; set; }
        public int x { get; set; }
        public int y { get; set; }
        public int z { get; set; }
        public sbyte chance { get; set; }
        public float maxzdiff { get; set; }
        public float radius { get; set; }
        public int effect { get; set; }
        public int effectvalue { get; set; }
        public int effectvalue2 { get; set; }
        public string message { get; set; }
        public int skill { get; set; }
        public int level { get; set; }
        public long respawn_time { get; set; }
        public long respawn_var { get; set; }
    }
}
