//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class veteran_reward_templates
    {
        public long claim_id { get; set; }
        public string name { get; set; }
        public long item_id { get; set; }
        public int charges { get; set; }
        public byte reward_slot { get; set; }
    }
}
