//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vspawnloc
    {
        public string name { get; set; }
        public string zone { get; set; }
        public float Spawn2X { get; set; }
        public float Spawn2Y { get; set; }
        public float Spawn2Z { get; set; }
        public string spawngroup_name { get; set; }
        public int Spawngroup_id { get; set; }
        public float Spawngroup_minX { get; set; }
        public float Spawngroup_maxX { get; set; }
        public float Spawngroup_minY { get; set; }
        public float Spawngroup_maxY { get; set; }
        public float Spawngroup_dist { get; set; }
        public int Spawngroup_mindelay { get; set; }
        public int Spawngroup_delay { get; set; }
    }
}
