//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bot_character_mobs
    {
        public string mob_type { get; set; }
        public long id { get; set; }
        public string name { get; set; }
        public byte @class { get; set; }
        public long level { get; set; }
        public long last_login { get; set; }
        public long zone_id { get; set; }
    }
}
