//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bot_groups
    {
        public long groups_index { get; set; }
        public string group_name { get; set; }
        public long group_leader_id { get; set; }
        public string group_leader_name { get; set; }
        public long owner_id { get; set; }
        public string owner_name { get; set; }
    }
}
