//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_groups
    {
        public int group_id { get; set; }
        public string mob_type { get; set; }
        public string name { get; set; }
        public int mob_id { get; set; }
        public Nullable<decimal> level { get; set; }
    }
}
