//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone_server
    {
        public string name { get; set; }
        public string address { get; set; }
        public int port { get; set; }
        public int player_count { get; set; }
        public System.DateTime last_alive { get; set; }
        public string rain { get; set; }
    }
}
