//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone_points
    {
        public int id { get; set; }
        public string zone { get; set; }
        public long version { get; set; }
        public int number { get; set; }
        public float y { get; set; }
        public float x { get; set; }
        public float z { get; set; }
        public float heading { get; set; }
        public float target_y { get; set; }
        public float target_x { get; set; }
        public float target_z { get; set; }
        public float target_heading { get; set; }
        public Nullable<int> zoneinst { get; set; }
        public long target_zone_id { get; set; }
        public long target_instance { get; set; }
        public float buffer { get; set; }
        public long client_version_mask { get; set; }
    }
}
