//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone_state_dump
    {
        public string zonename { get; set; }
        public long spawn2_count { get; set; }
        public long npc_count { get; set; }
        public long npcloot_count { get; set; }
        public long gmspawntype_count { get; set; }
        public byte[] spawn2 { get; set; }
        public byte[] npcs { get; set; }
        public byte[] npc_loot { get; set; }
        public byte[] gmspawntype { get; set; }
        public System.DateTime time { get; set; }
    }
}
