//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQEmu_Toolkit.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone
    {
        public string short_name { get; set; }
        public int id { get; set; }
        public string file_name { get; set; }
        public string long_name { get; set; }
        public string map_file_name { get; set; }
        public float safe_x { get; set; }
        public float safe_y { get; set; }
        public float safe_z { get; set; }
        public float graveyard_id { get; set; }
        public byte min_level { get; set; }
        public byte min_status { get; set; }
        public int zoneidnumber { get; set; }
        public byte version { get; set; }
        public int timezone { get; set; }
        public int maxclients { get; set; }
        public long ruleset { get; set; }
        public string note { get; set; }
        public float underworld { get; set; }
        public float minclip { get; set; }
        public float maxclip { get; set; }
        public float fog_minclip { get; set; }
        public float fog_maxclip { get; set; }
        public byte fog_blue { get; set; }
        public byte fog_red { get; set; }
        public byte fog_green { get; set; }
        public byte sky { get; set; }
        public byte ztype { get; set; }
        public decimal zone_exp_multiplier { get; set; }
        public float walkspeed { get; set; }
        public byte time_type { get; set; }
        public byte fog_red1 { get; set; }
        public byte fog_green1 { get; set; }
        public byte fog_blue1 { get; set; }
        public float fog_minclip1 { get; set; }
        public float fog_maxclip1 { get; set; }
        public byte fog_red2 { get; set; }
        public byte fog_green2 { get; set; }
        public byte fog_blue2 { get; set; }
        public float fog_minclip2 { get; set; }
        public float fog_maxclip2 { get; set; }
        public byte fog_red3 { get; set; }
        public byte fog_green3 { get; set; }
        public byte fog_blue3 { get; set; }
        public float fog_minclip3 { get; set; }
        public float fog_maxclip3 { get; set; }
        public byte fog_red4 { get; set; }
        public byte fog_green4 { get; set; }
        public byte fog_blue4 { get; set; }
        public float fog_minclip4 { get; set; }
        public float fog_maxclip4 { get; set; }
        public float fog_density { get; set; }
        public string flag_needed { get; set; }
        public sbyte canbind { get; set; }
        public sbyte cancombat { get; set; }
        public sbyte canlevitate { get; set; }
        public sbyte castoutdoor { get; set; }
        public byte hotzone { get; set; }
        public bool insttype { get; set; }
        public decimal shutdowndelay { get; set; }
        public sbyte peqzone { get; set; }
        public sbyte expansion { get; set; }
        public bool suspendbuffs { get; set; }
        public int rain_chance1 { get; set; }
        public int rain_chance2 { get; set; }
        public int rain_chance3 { get; set; }
        public int rain_chance4 { get; set; }
        public int rain_duration1 { get; set; }
        public int rain_duration2 { get; set; }
        public int rain_duration3 { get; set; }
        public int rain_duration4 { get; set; }
        public int snow_chance1 { get; set; }
        public int snow_chance2 { get; set; }
        public int snow_chance3 { get; set; }
        public int snow_chance4 { get; set; }
        public int snow_duration1 { get; set; }
        public int snow_duration2 { get; set; }
        public int snow_duration3 { get; set; }
        public int snow_duration4 { get; set; }
        public float gravity { get; set; }
        public int type { get; set; }
        public sbyte skylock { get; set; }
    }
}
